### PR TITLE
cj123/assetto-server-manager#271: Allow users to set LOCKED_ENTRY_LIST and PICKUP_MODE separately as they want

### PR DESCRIPTION
**Pull request by WraithStar**
The issue comes directly from Kunos, there's not much we can do. Kunos is not dropping any further AC updates anyway.

We pretty much confirmed both options have their own different problems, at this point letting the user decide which setting to go for is the best option, IMO.

### CODE REVIEW

**Comment by cj123** [comment]
My worry about doing it like this is that Championships do their own things with these settings. Presenting this option in a Championship event will cause confusion, especially if it's not applied.

Also, I don't know how I feel about the descriptions for both being near-identical - it doesn't seem like this informs the user any better than what we have now?

**Comment by WraithStar** [comment]
> 
> 
> My worry about doing it like this is that Championships do their own things with these settings. Presenting this option in a Championship event will cause confusion, especially if it's not applied.
>
>
> Also, I don't know how I feel about the descriptions for both being near-identical - it doesn't seem like this informs the user any better than what we have now?

This whole thing creates a lot of confusion by itself even in single events, but it's Kunos that messed up here, and I don't think there's much we can do in order to fix their mess.
The descriptions are identical because it's pretty much the same thing, it's just that as I wrote, one is broken in some ways, the other one is broken in other ways.

Perhaps we could better tell users in which ways they are broken, this is the only thing we can do, as far as I see it.

**Comment by WraithStar** [comment]
Actually there would be another way: automatically switch between LOCKED_ENTRY_LIST and PICKUP_MODE_ENABLED according to what kind of event the user is starting. 

If we have a 2-race event, we automatically switch LOCKED_ENTRY_LIST on and PICKUP_MODE_ENABLED off, and vice versa for any other event.

This would allow the user to only see a single switch.

**Comment by cj123** [comment]
@WraithStar I see that you've removed the "Note, when Locked Entry List is ON, sessions with Loop Mode ON will require players to rejoin the server when the server loops." 

I think this actually related to pickup mode, so perhaps pickup mode needs a 

"Note, when Pickup Mode is OFF, sessions with Loop Mode ON will require players to rejoin the server when the server loops."

**Comment by cj123** [comment]
Also, my worries about Championships are alleviated - I don't think any of this code could cause problems with it

**Comment by WraithStar** [comment]
Yeah even I am getting confused by this whole mess....
Anyway, updating as you suggested.

**Comment by cj123** [comment]
Thanks for this - lets see how it plays out :D

**Pull request merged**
