### PR TITLE
discord integration

### PR DESCRIPTION
**Pull request by cheesegrits**
OK, second attempt at this PR, with a fresh branch, no assetto/ folder problems.

### CODE REVIEW

**Comment by cheesegrits** [comment]
It's now building and testing cleanly, after a fix for the championship manager test (added a dummyNotificationManager).

**Comment by cj123** [comment]
Hi @cheesegrits, thanks for this. We'll have a look at this today and hopefully get it approved. From a quick glance, things are looking good :+1:

**Comment by cj123** [comment]
In general, i'm happy with the code quality across the board here. We have a couple of things we'd like to see fixed now to get this merged:

1) Handling of events with no specific event name
2) Initial setup of Discord integration requires a full server manager restart to make it work. There's a few options here:
    a) in the help text, tell the user that initial setup requires a restart
    b) when server options are saved, reconfigure the bot (I think this is my preference)
    c) when server options are saved, trigger a restart of server manager (this could be a bit dangerous if events are running etc, would need user confirmation)
3) It looks like maybe the `!schedule` command is broken, but maybe that's due to my setup? If so, we definitely need to note that somewhere...

That leads me onto a 'nice to have' which I think would be a post in the Wiki that explains how to set up discord integration. Ideally we could have the help text in server manager linking to a page that explains it.

**Comment by cheesegrits** [comment]
Re 2.b, I was actually in the middle of posting an issue/request, on how I can hook in to the options being saved, so I can a) start/restart the Discord bot if need be, and b) re-schedule notifications if the notification timer is changed,

**Comment by cj123** [comment]
Either server_administration.go "options" method, or race manager "SaveServerOptions" would be the right place to do that, I think

**Comment by cheesegrits** [comment]
So add a specific call to the NotificationManager in there, or build some kind of callback handler that anything can register with?  I've not looked at how callbacks work in Go.

**Comment by cj123** [comment]
i'd just go with the specific call - I haven't seen enough of a need to do callbacks yet

**Comment by cheesegrits** [comment]
OK ... and I think I'd need to pass two versions of the server options ... pre and post change.

**Comment by cheesegrits** [comment]
@cj123 I committed the code to have the notification manager dispatch option checks, and the Dicord manager will now start/stop as necessary, without needing a server restart.

The only thing I'm not really sure about is the changes to the RaceManager SaveServerOptions() ... I'm not convinced it should error out if it can't read old options or if the NotificationManager SaveServerOptions()errors out.  It should probably ignore those errors and go ahead and save the new options regardless ... thoughts?

I'll add handling empty names later today.

**Comment by cheesegrits** [comment]
With the !schedule command ... I don't know.  I thought maybe it was something to do with your server setup, maybe firewall issues ... but it works on my local dev system, which is a VM running Ubuntu running ufw, sitting on a Windows box running the Windows firewall, sitting behind a domestic NAT'ing router which also firewalls.  So probably not.

What permissions did you give your bot?  I have no idea if it needs specific permissions ... this is my first bot.

**Comment by cheesegrits** [comment]
Added some code to reschedule the notification reminders if the reminder timer is changed

**Comment by cj123** [comment]
> What permissions did you give your bot? I have no idea if it needs specific permissions ... this is my first bot.

all of them, I think :D

**Comment by cheesegrits** [comment]
Don't know what the deal is with the !schedule.  It works fine on my test and live sites.  I'd suggest we simply don't publicize that as a feature yet (or just designate it as WIP), and I work on it as part of the next set of improvements.  Hopefully having some more sites out in the wild using this, I'd have a better chance of tracking down the issue.

I'll go ahead and create a wiki page for this as soon as I have some time.

BTW, with the new RaceManager RescheduleReminders() ... I would rather have put that in the NotificationManager, called as part of the existing SaveServerOptions(), but that was another circular dependency thing .... the NotificationManager would have needed the RaceManager in the resolver, and the RaceManager already needs the NotificationManager.

**Comment by cj123** [comment]
@cheesegrits your "TODO" isn't a memory leak, it will be fine :)

Don't worry too much about the RescheduleReminders() method, I probably have some unravelling of our existing code to do to sort out these circular dependency issues

**Comment by cheesegrits** [comment]
Just merged master into it again ... had some conflicts with some vendor stuff, think it's all resolved.

**Comment by cheesegrits** [comment]
@cj123 how do you want to handle images for a wiki page?  In the past, I've used that trick of uploading an image into a new issue, copying the raw githubusercontent URL (without submitting the issue) and relying on the image just existing forever in the ether.  But you may prefer to actually commit images into the main repo.

I've never actually worked with a wiki in someone else's repo before, and turns out it's not exactly easy.  Although it's possible to clone a wiki repo, you can't submit PR's on them.

I see that you have your wiki open, so I can create pages, but there's no clear, standard way of handling embedded images.

**Comment by cj123** [comment]
@cheesegrits sorry for the slow response on this one...

Imgur uploading of the images should be fine? I don't think they have too much of a habit of disappearing?

Yeah, the wiki is open, edit as you like :)

Is the code ready to take another look at?

**Comment by cheesegrits** [comment]
Looks like I need to merge another commit, but once that's done, yup, should be good.

I still have no idea why your !schedule command doesn't work, see my previous comment about that.  It works fine on both my servers, so I suggest we just flag that feature as WIP for the moment, get some more sites in the wild running it, give me more to go on.

The only feature I'm not sure about atm is the notification when an event is scheduled.  I want that behavior, but others may not.  So it should probably be an option, which I could easily add, but ... I already feel like I'm hogging up too much space in the main server options.  Thoughts?

**Comment by cheesegrits** [comment]
Oh, and wrt the ! cmd handler ... I'd like to expand that in the next phase of development, beyond the basic scheduling, with things like !standings, !results, etc.  So I'll definitely be doing more work on it, and can figure out what your issue is.

**Comment by cheesegrits** [comment]
@cj123 OK, upstream master merged.

There's also a question in one of my previous comments about error handling in SaveServerOptions() that could do with some code review.  Nutshell, I probably should bang out if the new calls to the notification manager fail, just log the errors and let the main save happen regardless.

**Comment by cj123** [comment]
The ServerOptions thing - i'd return the errors and not continue the process I think. The likelihood of such things happening is low, but if something did go wrong, i'd rather it be known about.

**Comment by cheesegrits** [comment]
@cj123 I think my explanation wasn't clear.  I do return the errors, the issue is whether I should exit after reading the old options.  If you look at the diff for race_manager ...

https://github.com/cj123/assetto-server-manager/pull/496/commits/b7d97297cf98fc3e8f8e67074bdb88982b2c5641

... you'll see I've added reading the "old" (prior to being upserted) options, before the upsert, so I have the pre-change options I can pass to the notification manager as well as the new (changed) options, so the notification / discord manager(s) can figure out what has actually been changed.

What I'm not convinced about is whether, if reading the old options errors out, I should bang out of SaveServerOptions.  That could lead to a situation where you can't save the new options, simply because the old options can't be read.

Yup, very unlikely it would happen, but you know how those "one in a million" things have a habit of happening.  :)

Other than that small thing, it's ready for another look.

**Pull request merged**
