### PR TITLE
Discord integration

### PR DESCRIPTION
**Pull request by cheesegrits**
As per issue https://github.com/cj123/assetto-server-manager/issues/456, here is the initial PR.

Obviously needs review.

### CODE REVIEW

**Comment by cj123** [comment]
Hi, Thanks for the PR.

I see the entire assetto folder is in your commit history. We don't want this in our merge and it needs to be removed from history entirely. 

Something like this may be of use: https://myopswork.com/how-remove-files-completely-from-git-repository-history-47ed3e0c4c35

**Comment by cheesegrits** [comment]
Yeah, I had assumed assetto/ would be in gitignore when I started.  Didn't notice till after the first commit.  Added it to gitignore, but obviously too late.

I'm going to try this approach:

https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

**Comment by cheesegrits** [comment]
As far as I can tell, it's removed.

**Comment by cheesegrits** [comment]
Ooops, had to merge master in again.

**Comment by cheesegrits** [comment]
*sigh*

Looking at the commit list and changed files, I think I just need to start again.  I don't know wtf went on with that attempt to clean out /assetto from the history.  I need to make a clean clone of master, make a new discord branch, use some external tool to merge all my changes in, and re-submit the PR.

**Pull request closed without merging**
